// Autogenerated with StateSmith 0.22.2+0c32be37bf4d4fee5499780a5ef37a7996c192f9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#nullable enable

using System;


namespace MegaManZero
{
    // Generated state machine
    public partial class PlayerSm
    {
        public enum EventId
        {
            DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
            APEX = 1,
            ATTACK_FINISHED = 2,
            ATTACK_PRESS = 3,
            CHARGE_RELEASE = 4,
            DASH_FINISHED = 5,
            DASH_PRESS = 6,
            FALL = 7,
            JUMP_PRESS = 8,
            LANDED = 9,
            MOVE_INPUT = 10,
            STOP_INPUT = 11,
            WALL_DETACH = 12,
            WALL_TOUCH = 13,
        }

        public const int EventIdCount = 14;

        public enum StateId
        {
            ROOT = 0,
            AIRBORNE = 1,
            ATTACK_AIR = 2,
            FALL = 3,
            JUMP = 4,
            GROUNDED = 5,
            ATTACK_1 = 6,
            ATTACK_2 = 7,
            ATTACK_3 = 8,
            ATTACK_DASH = 9,
            ATTACK_RUN = 10,
            CHARGE_SLASH = 11,
            DASH = 12,
            IDLE = 13,
            RUN = 14,
            WALL_SLIDE = 15,
            ATTACK_GRAB_WALL = 16,
            GRAB_WALL = 17,
        }

        public const int StateIdCount = 18;

        // Subtree meta data generation can be disabled in settings.
        // Details: https://github.com/StateSmith/StateSmith/issues/538
        public const int ROOT_SubtreeEndId = 17;  // State 'PlayerSm' subtree extends from itself (id: 0) to state 'GRAB_WALL' (id: 17)
        public const int AIRBORNE_SubtreeEndId = 4;  // State 'AIRBORNE' subtree extends from itself (id: 1) to state 'JUMP' (id: 4)
        public const int ATTACK_AIR_SubtreeEndId = 2;  // State 'ATTACK_AIR' subtree extends from itself (id: 2) to state 'ATTACK_AIR' (id: 2)
        public const int FALL_SubtreeEndId = 3;  // State 'FALL' subtree extends from itself (id: 3) to state 'FALL' (id: 3)
        public const int JUMP_SubtreeEndId = 4;  // State 'JUMP' subtree extends from itself (id: 4) to state 'JUMP' (id: 4)
        public const int GROUNDED_SubtreeEndId = 14;  // State 'GROUNDED' subtree extends from itself (id: 5) to state 'RUN' (id: 14)
        public const int ATTACK_1_SubtreeEndId = 6;  // State 'ATTACK_1' subtree extends from itself (id: 6) to state 'ATTACK_1' (id: 6)
        public const int ATTACK_2_SubtreeEndId = 7;  // State 'ATTACK_2' subtree extends from itself (id: 7) to state 'ATTACK_2' (id: 7)
        public const int ATTACK_3_SubtreeEndId = 8;  // State 'ATTACK_3' subtree extends from itself (id: 8) to state 'ATTACK_3' (id: 8)
        public const int ATTACK_DASH_SubtreeEndId = 9;  // State 'ATTACK_DASH' subtree extends from itself (id: 9) to state 'ATTACK_DASH' (id: 9)
        public const int ATTACK_RUN_SubtreeEndId = 10;  // State 'ATTACK_RUN' subtree extends from itself (id: 10) to state 'ATTACK_RUN' (id: 10)
        public const int CHARGE_SLASH_SubtreeEndId = 11;  // State 'CHARGE_SLASH' subtree extends from itself (id: 11) to state 'CHARGE_SLASH' (id: 11)
        public const int DASH_SubtreeEndId = 12;  // State 'DASH' subtree extends from itself (id: 12) to state 'DASH' (id: 12)
        public const int IDLE_SubtreeEndId = 13;  // State 'IDLE' subtree extends from itself (id: 13) to state 'IDLE' (id: 13)
        public const int RUN_SubtreeEndId = 14;  // State 'RUN' subtree extends from itself (id: 14) to state 'RUN' (id: 14)
        public const int WALL_SLIDE_SubtreeEndId = 17;  // State 'WALL_SLIDE' subtree extends from itself (id: 15) to state 'GRAB_WALL' (id: 17)
        public const int ATTACK_GRAB_WALL_SubtreeEndId = 16;  // State 'ATTACK_GRAB_WALL' subtree extends from itself (id: 16) to state 'ATTACK_GRAB_WALL' (id: 16)
        public const int GRAB_WALL_SubtreeEndId = 17;  // State 'GRAB_WALL' subtree extends from itself (id: 17) to state 'GRAB_WALL' (id: 17)

        // Used internally by state machine. Feel free to inspect, but don't modify.
        public StateId stateId;

        // State machine variables. Can be used for inputs, outputs, user variables...
        public struct Vars
        {
            public float vx;
            public float vy;
            public float dashTimer;
            public bool isGrounded;
            public bool isTouchingWall;
            public int facing;
        }

        // Variables. Can be used for inputs, outputs, user variables...
        public Vars vars = new Vars();

        // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
        public PlayerSm()
        {
        }

        // Starts the state machine. Must be called before dispatching events. Not thread safe.
        public void Start()
        {
            ROOT_enter();
            // ROOT behavior
            // uml: TransitionTo(ROOT.<InitialState>)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
                // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.

                // ROOT.<InitialState> behavior
                // uml: TransitionTo(GROUNDED)
                {
                    // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                    // Step 2: Transition action: ``.

                    // Step 3: Enter/move towards transition target `GROUNDED`.
                    GROUNDED_enter();

                    // Finish transition by calling pseudo state transition function.
                    GROUNDED_InitialState_transition();
                    return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
                } // end of behavior for ROOT.<InitialState>
            } // end of behavior for ROOT
        }

        // Dispatches an event to the state machine. Not thread safe.
        // Note! This function assumes that the `eventId` parameter is valid.
        public void DispatchEvent(EventId eventId)
        {
            switch (this.stateId)
            {
                // STATE: PlayerSm
                case StateId.ROOT:
                    // No events handled by this state (or its ancestors).
                    break;

                // STATE: AIRBORNE
                case StateId.AIRBORNE:
                    switch (eventId)
                    {
                        case EventId.LANDED: AIRBORNE_landed(); break;
                        case EventId.WALL_TOUCH: AIRBORNE_wall_touch(); break;
                    }
                    break;

                // STATE: ATTACK_AIR
                case StateId.ATTACK_AIR:
                    switch (eventId)
                    {
                        case EventId.DO: ATTACK_AIR_do(); break;
                        case EventId.ATTACK_FINISHED: ATTACK_AIR_attack_finished(); break;
                        case EventId.LANDED: AIRBORNE_landed(); break; // First ancestor handler for this event
                        case EventId.WALL_TOUCH: AIRBORNE_wall_touch(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: FALL
                case StateId.FALL:
                    switch (eventId)
                    {
                        case EventId.DO: FALL_do(); break;
                        case EventId.ATTACK_PRESS: FALL_attack_press(); break;
                        case EventId.LANDED: AIRBORNE_landed(); break; // First ancestor handler for this event
                        case EventId.WALL_TOUCH: AIRBORNE_wall_touch(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: JUMP
                case StateId.JUMP:
                    switch (eventId)
                    {
                        case EventId.DO: JUMP_do(); break;
                        case EventId.APEX: JUMP_apex(); break;
                        case EventId.ATTACK_PRESS: JUMP_attack_press(); break;
                        case EventId.LANDED: AIRBORNE_landed(); break; // First ancestor handler for this event
                        case EventId.WALL_TOUCH: AIRBORNE_wall_touch(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: GROUNDED
                case StateId.GROUNDED:
                    switch (eventId)
                    {
                        case EventId.JUMP_PRESS: GROUNDED_jump_press(); break;
                        case EventId.FALL: GROUNDED_fall(); break;
                    }
                    break;

                // STATE: ATTACK_1
                case StateId.ATTACK_1:
                    switch (eventId)
                    {
                        case EventId.ATTACK_FINISHED: ATTACK_1_attack_finished(); break;
                        case EventId.ATTACK_PRESS: ATTACK_1_attack_press(); break;
                        case EventId.JUMP_PRESS: GROUNDED_jump_press(); break; // First ancestor handler for this event
                        case EventId.FALL: GROUNDED_fall(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: ATTACK_2
                case StateId.ATTACK_2:
                    switch (eventId)
                    {
                        case EventId.ATTACK_PRESS: ATTACK_2_attack_press(); break;
                        case EventId.ATTACK_FINISHED: ATTACK_2_attack_finished(); break;
                        case EventId.JUMP_PRESS: GROUNDED_jump_press(); break; // First ancestor handler for this event
                        case EventId.FALL: GROUNDED_fall(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: ATTACK_3
                case StateId.ATTACK_3:
                    switch (eventId)
                    {
                        case EventId.ATTACK_FINISHED: ATTACK_3_attack_finished(); break;
                        case EventId.JUMP_PRESS: GROUNDED_jump_press(); break; // First ancestor handler for this event
                        case EventId.FALL: GROUNDED_fall(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: ATTACK_DASH
                case StateId.ATTACK_DASH:
                    switch (eventId)
                    {
                        case EventId.DO: ATTACK_DASH_do(); break;
                        case EventId.ATTACK_FINISHED: ATTACK_DASH_attack_finished(); break;
                        case EventId.JUMP_PRESS: GROUNDED_jump_press(); break; // First ancestor handler for this event
                        case EventId.FALL: GROUNDED_fall(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: ATTACK_RUN
                case StateId.ATTACK_RUN:
                    switch (eventId)
                    {
                        case EventId.DO: ATTACK_RUN_do(); break;
                        case EventId.ATTACK_FINISHED: ATTACK_RUN_attack_finished(); break;
                        case EventId.JUMP_PRESS: GROUNDED_jump_press(); break; // First ancestor handler for this event
                        case EventId.FALL: GROUNDED_fall(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: CHARGE_SLASH
                case StateId.CHARGE_SLASH:
                    switch (eventId)
                    {
                        case EventId.ATTACK_FINISHED: CHARGE_SLASH_attack_finished(); break;
                        case EventId.JUMP_PRESS: GROUNDED_jump_press(); break; // First ancestor handler for this event
                        case EventId.FALL: GROUNDED_fall(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: DASH
                case StateId.DASH:
                    switch (eventId)
                    {
                        case EventId.DO: DASH_do(); break;
                        case EventId.DASH_FINISHED: DASH_dash_finished(); break;
                        case EventId.ATTACK_PRESS: DASH_attack_press(); break;
                        case EventId.JUMP_PRESS: GROUNDED_jump_press(); break; // First ancestor handler for this event
                        case EventId.FALL: GROUNDED_fall(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: IDLE
                case StateId.IDLE:
                    switch (eventId)
                    {
                        case EventId.DO: IDLE_do(); break;
                        case EventId.MOVE_INPUT: IDLE_move_input(); break;
                        case EventId.ATTACK_PRESS: IDLE_attack_press(); break;
                        case EventId.CHARGE_RELEASE: IDLE_charge_release(); break;
                        case EventId.JUMP_PRESS: GROUNDED_jump_press(); break; // First ancestor handler for this event
                        case EventId.FALL: GROUNDED_fall(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: RUN
                case StateId.RUN:
                    switch (eventId)
                    {
                        case EventId.DO: RUN_do(); break;
                        case EventId.DASH_PRESS: RUN_dash_press(); break;
                        case EventId.STOP_INPUT: RUN_stop_input(); break;
                        case EventId.ATTACK_PRESS: RUN_attack_press(); break;
                        case EventId.CHARGE_RELEASE: RUN_charge_release(); break;
                        case EventId.JUMP_PRESS: GROUNDED_jump_press(); break; // First ancestor handler for this event
                        case EventId.FALL: GROUNDED_fall(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: WALL_SLIDE
                case StateId.WALL_SLIDE:
                    switch (eventId)
                    {
                        case EventId.JUMP_PRESS: WALL_SLIDE_jump_press(); break;
                        case EventId.WALL_DETACH: WALL_SLIDE_wall_detach(); break;
                        case EventId.LANDED: WALL_SLIDE_landed(); break;
                    }
                    break;

                // STATE: ATTACK_GRAB_WALL
                case StateId.ATTACK_GRAB_WALL:
                    switch (eventId)
                    {
                        case EventId.DO: ATTACK_GRAB_WALL_do(); break;
                        case EventId.ATTACK_FINISHED: ATTACK_GRAB_WALL_attack_finished(); break;
                        case EventId.JUMP_PRESS: WALL_SLIDE_jump_press(); break; // First ancestor handler for this event
                        case EventId.LANDED: WALL_SLIDE_landed(); break; // First ancestor handler for this event
                        case EventId.WALL_DETACH: WALL_SLIDE_wall_detach(); break; // First ancestor handler for this event
                    }
                    break;

                // STATE: GRAB_WALL
                case StateId.GRAB_WALL:
                    switch (eventId)
                    {
                        case EventId.DO: GRAB_WALL_do(); break;
                        case EventId.ATTACK_PRESS: GRAB_WALL_attack_press(); break;
                        case EventId.JUMP_PRESS: WALL_SLIDE_jump_press(); break; // First ancestor handler for this event
                        case EventId.LANDED: WALL_SLIDE_landed(); break; // First ancestor handler for this event
                        case EventId.WALL_DETACH: WALL_SLIDE_wall_detach(); break; // First ancestor handler for this event
                    }
                    break;
            }

        }

        // This function is used when StateSmith doesn't know what the active leaf state is at
        // compile time due to sub states or when multiple states need to be exited.
        private void ExitUpToStateHandler(StateId desiredState)
        {
            while (this.stateId != desiredState)
            {
                switch (this.stateId)
                {
                    case StateId.AIRBORNE: AIRBORNE_exit(); break;

                    case StateId.ATTACK_AIR: ATTACK_AIR_exit(); break;

                    case StateId.FALL: FALL_exit(); break;

                    case StateId.JUMP: JUMP_exit(); break;

                    case StateId.GROUNDED: GROUNDED_exit(); break;

                    case StateId.ATTACK_1: ATTACK_1_exit(); break;

                    case StateId.ATTACK_2: ATTACK_2_exit(); break;

                    case StateId.ATTACK_3: ATTACK_3_exit(); break;

                    case StateId.ATTACK_DASH: ATTACK_DASH_exit(); break;

                    case StateId.ATTACK_RUN: ATTACK_RUN_exit(); break;

                    case StateId.CHARGE_SLASH: CHARGE_SLASH_exit(); break;

                    case StateId.DASH: DASH_exit(); break;

                    case StateId.IDLE: IDLE_exit(); break;

                    case StateId.RUN: RUN_exit(); break;

                    case StateId.WALL_SLIDE: WALL_SLIDE_exit(); break;

                    case StateId.ATTACK_GRAB_WALL: ATTACK_GRAB_WALL_exit(); break;

                    case StateId.GRAB_WALL: GRAB_WALL_exit(); break;

                    default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
                }
            }
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state ROOT
        ////////////////////////////////////////////////////////////////////////////////

        private void ROOT_enter()
        {
            this.stateId = StateId.ROOT;
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state AIRBORNE
        ////////////////////////////////////////////////////////////////////////////////

        private void AIRBORNE_enter()
        {
            this.stateId = StateId.AIRBORNE;
        }

        private void AIRBORNE_exit()
        {
            this.stateId = StateId.ROOT;
        }

        private void AIRBORNE_landed()
        {
            // AIRBORNE behavior
            // uml: LANDED / { PlayAnim("seq_09_land"); } TransitionTo(GROUNDED)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                ExitUpToStateHandler(StateId.ROOT);

                // Step 2: Transition action: `PlayAnim("seq_09_land");`.
                PlayAnim("seq_09_land");

                // Step 3: Enter/move towards transition target `GROUNDED`.
                GROUNDED_enter();

                // Finish transition by calling pseudo state transition function.
                GROUNDED_InitialState_transition();
                return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
            } // end of behavior for AIRBORNE

            // No ancestor handles this event.
        }

        private void AIRBORNE_wall_touch()
        {
            // AIRBORNE behavior
            // uml: WALL_TOUCH [vars.vy > 0 && isTouchingWall] TransitionTo(WALL_SLIDE)
            if (vars.vy > 0 && isTouchingWall)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                ExitUpToStateHandler(StateId.ROOT);

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `WALL_SLIDE`.
                WALL_SLIDE_enter();

                // WALL_SLIDE.<InitialState> behavior
                // uml: TransitionTo(GRAB_WALL)
                {
                    // Step 1: Exit states until we reach `WALL_SLIDE` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                    // Step 2: Transition action: ``.

                    // Step 3: Enter/move towards transition target `GRAB_WALL`.
                    GRAB_WALL_enter();

                    // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                    return;
                } // end of behavior for WALL_SLIDE.<InitialState>
            } // end of behavior for AIRBORNE

            // No ancestor handles this event.
        }

        private void AIRBORNE_InitialState_transition()
        {
            // AIRBORNE.<InitialState> behavior
            // uml: TransitionTo(JUMP)
            {
                // Step 1: Exit states until we reach `AIRBORNE` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `JUMP`.
                JUMP_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for AIRBORNE.<InitialState>
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state ATTACK_AIR
        ////////////////////////////////////////////////////////////////////////////////

        private void ATTACK_AIR_enter()
        {
            this.stateId = StateId.ATTACK_AIR;

            // ATTACK_AIR behavior
            // uml: enter / { PlayAnim("seq_26_attack_air_jump_slash"); }
            {
                // Step 1: execute action `PlayAnim("seq_26_attack_air_jump_slash");`
                PlayAnim("seq_26_attack_air_jump_slash");
            } // end of behavior for ATTACK_AIR
        }

        private void ATTACK_AIR_exit()
        {
            this.stateId = StateId.AIRBORNE;
        }

        private void ATTACK_AIR_attack_finished()
        {
            // ATTACK_AIR behavior
            // uml: ATTACK_FINISHED TransitionTo(FALL)
            {
                // Step 1: Exit states until we reach `AIRBORNE` state (Least Common Ancestor for transition).
                ATTACK_AIR_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `FALL`.
                FALL_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ATTACK_AIR

            // No ancestor handles this event.
        }

        private void ATTACK_AIR_do()
        {
            // ATTACK_AIR behavior
            // uml: do / { ApplyAirControl(); }
            {
                // Step 1: execute action `ApplyAirControl();`
                ApplyAirControl();
            } // end of behavior for ATTACK_AIR

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state FALL
        ////////////////////////////////////////////////////////////////////////////////

        private void FALL_enter()
        {
            this.stateId = StateId.FALL;

            // FALL behavior
            // uml: enter / { PlayAnim("seq_10_jump_somersault"); }
            {
                // Step 1: execute action `PlayAnim("seq_10_jump_somersault");`
                PlayAnim("seq_10_jump_somersault");
            } // end of behavior for FALL
        }

        private void FALL_exit()
        {
            this.stateId = StateId.AIRBORNE;
        }

        private void FALL_attack_press()
        {
            // FALL behavior
            // uml: ATTACK_PRESS TransitionTo(ATTACK_AIR)
            {
                // Step 1: Exit states until we reach `AIRBORNE` state (Least Common Ancestor for transition).
                FALL_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `ATTACK_AIR`.
                ATTACK_AIR_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for FALL

            // No ancestor handles this event.
        }

        private void FALL_do()
        {
            // FALL behavior
            // uml: do / { ApplyAirControl(); }
            {
                // Step 1: execute action `ApplyAirControl();`
                ApplyAirControl();
            } // end of behavior for FALL

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state JUMP
        ////////////////////////////////////////////////////////////////////////////////

        private void JUMP_enter()
        {
            this.stateId = StateId.JUMP;

            // JUMP behavior
            // uml: enter / { PlayAnim("seq_08_jump"); }
            {
                // Step 1: execute action `PlayAnim("seq_08_jump");`
                PlayAnim("seq_08_jump");
            } // end of behavior for JUMP
        }

        private void JUMP_exit()
        {
            this.stateId = StateId.AIRBORNE;
        }

        private void JUMP_apex()
        {
            // JUMP behavior
            // uml: APEX [vy >= 0] TransitionTo(FALL)
            if (vy >= 0)
            {
                // Step 1: Exit states until we reach `AIRBORNE` state (Least Common Ancestor for transition).
                JUMP_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `FALL`.
                FALL_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for JUMP

            // No ancestor handles this event.
        }

        private void JUMP_attack_press()
        {
            // JUMP behavior
            // uml: ATTACK_PRESS TransitionTo(ATTACK_AIR)
            {
                // Step 1: Exit states until we reach `AIRBORNE` state (Least Common Ancestor for transition).
                JUMP_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `ATTACK_AIR`.
                ATTACK_AIR_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for JUMP

            // No ancestor handles this event.
        }

        private void JUMP_do()
        {
            // JUMP behavior
            // uml: do / { ApplyAirControl(); }
            {
                // Step 1: execute action `ApplyAirControl();`
                ApplyAirControl();
            } // end of behavior for JUMP

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state GROUNDED
        ////////////////////////////////////////////////////////////////////////////////

        private void GROUNDED_enter()
        {
            this.stateId = StateId.GROUNDED;
        }

        private void GROUNDED_exit()
        {
            this.stateId = StateId.ROOT;
        }

        private void GROUNDED_fall()
        {
            // GROUNDED behavior
            // uml: FALL [!isGrounded] TransitionTo(AIRBORNE)
            if (!isGrounded)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                ExitUpToStateHandler(StateId.ROOT);

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `AIRBORNE`.
                AIRBORNE_enter();

                // Finish transition by calling pseudo state transition function.
                AIRBORNE_InitialState_transition();
                return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
            } // end of behavior for GROUNDED

            // No ancestor handles this event.
        }

        private void GROUNDED_jump_press()
        {
            // GROUNDED behavior
            // uml: JUMP_PRESS / { ApplyJumpImpulse(); } TransitionTo(AIRBORNE)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                ExitUpToStateHandler(StateId.ROOT);

                // Step 2: Transition action: `ApplyJumpImpulse();`.
                ApplyJumpImpulse();

                // Step 3: Enter/move towards transition target `AIRBORNE`.
                AIRBORNE_enter();

                // Finish transition by calling pseudo state transition function.
                AIRBORNE_InitialState_transition();
                return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
            } // end of behavior for GROUNDED

            // No ancestor handles this event.
        }

        private void GROUNDED_InitialState_transition()
        {
            // GROUNDED.<InitialState> behavior
            // uml: TransitionTo(IDLE)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `IDLE`.
                IDLE_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for GROUNDED.<InitialState>
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state ATTACK_1
        ////////////////////////////////////////////////////////////////////////////////

        private void ATTACK_1_enter()
        {
            this.stateId = StateId.ATTACK_1;

            // ATTACK_1 behavior
            // uml: enter / { PlayAnim("seq_17_saber_slash_1"); }
            {
                // Step 1: execute action `PlayAnim("seq_17_saber_slash_1");`
                PlayAnim("seq_17_saber_slash_1");
            } // end of behavior for ATTACK_1

            // ATTACK_1 behavior
            // uml: enter / { StartAttackHitbox(); }
            {
                // Step 1: execute action `StartAttackHitbox();`
                StartAttackHitbox();
            } // end of behavior for ATTACK_1
        }

        private void ATTACK_1_exit()
        {
            // ATTACK_1 behavior
            // uml: exit / { EndAttackHitbox(); }
            {
                // Step 1: execute action `EndAttackHitbox();`
                EndAttackHitbox();
            } // end of behavior for ATTACK_1

            this.stateId = StateId.GROUNDED;
        }

        private void ATTACK_1_attack_finished()
        {
            // ATTACK_1 behavior
            // uml: ATTACK_FINISHED TransitionTo(IDLE)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                ATTACK_1_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `IDLE`.
                IDLE_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ATTACK_1

            // No ancestor handles this event.
        }

        private void ATTACK_1_attack_press()
        {
            // ATTACK_1 behavior
            // uml: ATTACK_PRESS TransitionTo(ATTACK_2)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                ATTACK_1_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `ATTACK_2`.
                ATTACK_2_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ATTACK_1

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state ATTACK_2
        ////////////////////////////////////////////////////////////////////////////////

        private void ATTACK_2_enter()
        {
            this.stateId = StateId.ATTACK_2;

            // ATTACK_2 behavior
            // uml: enter / { PlayAnim("seq_18_saber_slash_1"); }
            {
                // Step 1: execute action `PlayAnim("seq_18_saber_slash_1");`
                PlayAnim("seq_18_saber_slash_1");
            } // end of behavior for ATTACK_2

            // ATTACK_2 behavior
            // uml: enter / { StartAttackHitbox(); }
            {
                // Step 1: execute action `StartAttackHitbox();`
                StartAttackHitbox();
            } // end of behavior for ATTACK_2
        }

        private void ATTACK_2_exit()
        {
            // ATTACK_2 behavior
            // uml: exit / { EndAttackHitbox(); }
            {
                // Step 1: execute action `EndAttackHitbox();`
                EndAttackHitbox();
            } // end of behavior for ATTACK_2

            this.stateId = StateId.GROUNDED;
        }

        private void ATTACK_2_attack_finished()
        {
            // ATTACK_2 behavior
            // uml: ATTACK_FINISHED TransitionTo(IDLE)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                ATTACK_2_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `IDLE`.
                IDLE_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ATTACK_2

            // No ancestor handles this event.
        }

        private void ATTACK_2_attack_press()
        {
            // ATTACK_2 behavior
            // uml: ATTACK_PRESS TransitionTo(ATTACK_3)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                ATTACK_2_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `ATTACK_3`.
                ATTACK_3_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ATTACK_2

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state ATTACK_3
        ////////////////////////////////////////////////////////////////////////////////

        private void ATTACK_3_enter()
        {
            this.stateId = StateId.ATTACK_3;

            // ATTACK_3 behavior
            // uml: enter / { PlayAnim("seq_21_saber_slash_1"); }
            {
                // Step 1: execute action `PlayAnim("seq_21_saber_slash_1");`
                PlayAnim("seq_21_saber_slash_1");
            } // end of behavior for ATTACK_3

            // ATTACK_3 behavior
            // uml: enter / { StartAttackHitbox(); }
            {
                // Step 1: execute action `StartAttackHitbox();`
                StartAttackHitbox();
            } // end of behavior for ATTACK_3
        }

        private void ATTACK_3_exit()
        {
            // ATTACK_3 behavior
            // uml: exit / { EndAttackHitbox(); }
            {
                // Step 1: execute action `EndAttackHitbox();`
                EndAttackHitbox();
            } // end of behavior for ATTACK_3

            this.stateId = StateId.GROUNDED;
        }

        private void ATTACK_3_attack_finished()
        {
            // ATTACK_3 behavior
            // uml: ATTACK_FINISHED TransitionTo(IDLE)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                ATTACK_3_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `IDLE`.
                IDLE_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ATTACK_3

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state ATTACK_DASH
        ////////////////////////////////////////////////////////////////////////////////

        private void ATTACK_DASH_enter()
        {
            this.stateId = StateId.ATTACK_DASH;

            // ATTACK_DASH behavior
            // uml: enter / { PlayAnim("seq_27_attack_dash_slash"); }
            {
                // Step 1: execute action `PlayAnim("seq_27_attack_dash_slash");`
                PlayAnim("seq_27_attack_dash_slash");
            } // end of behavior for ATTACK_DASH
        }

        private void ATTACK_DASH_exit()
        {
            this.stateId = StateId.GROUNDED;
        }

        private void ATTACK_DASH_attack_finished()
        {
            // ATTACK_DASH behavior
            // uml: ATTACK_FINISHED TransitionTo(DASH)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                ATTACK_DASH_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `DASH`.
                DASH_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ATTACK_DASH

            // No ancestor handles this event.
        }

        private void ATTACK_DASH_do()
        {
            // ATTACK_DASH behavior
            // uml: do / { ApplyRunVelocity(); }
            {
                // Step 1: execute action `ApplyRunVelocity();`
                ApplyRunVelocity();
            } // end of behavior for ATTACK_DASH

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state ATTACK_RUN
        ////////////////////////////////////////////////////////////////////////////////

        private void ATTACK_RUN_enter()
        {
            this.stateId = StateId.ATTACK_RUN;

            // ATTACK_RUN behavior
            // uml: enter / { PlayAnim("seq_25_attack_walk_slash"); }
            {
                // Step 1: execute action `PlayAnim("seq_25_attack_walk_slash");`
                PlayAnim("seq_25_attack_walk_slash");
            } // end of behavior for ATTACK_RUN
        }

        private void ATTACK_RUN_exit()
        {
            this.stateId = StateId.GROUNDED;
        }

        private void ATTACK_RUN_attack_finished()
        {
            // ATTACK_RUN behavior
            // uml: ATTACK_FINISHED TransitionTo(RUN)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                ATTACK_RUN_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `RUN`.
                RUN_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ATTACK_RUN

            // No ancestor handles this event.
        }

        private void ATTACK_RUN_do()
        {
            // ATTACK_RUN behavior
            // uml: do / { ApplyRunVelocity(); }
            {
                // Step 1: execute action `ApplyRunVelocity();`
                ApplyRunVelocity();
            } // end of behavior for ATTACK_RUN

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state CHARGE_SLASH
        ////////////////////////////////////////////////////////////////////////////////

        private void CHARGE_SLASH_enter()
        {
            this.stateId = StateId.CHARGE_SLASH;

            // CHARGE_SLASH behavior
            // uml: enter / { PlayAnim("seq_20_saber_slash_1"); }
            {
                // Step 1: execute action `PlayAnim("seq_20_saber_slash_1");`
                PlayAnim("seq_20_saber_slash_1");
            } // end of behavior for CHARGE_SLASH

            // CHARGE_SLASH behavior
            // uml: enter / { StartAttackHitbox(); }
            {
                // Step 1: execute action `StartAttackHitbox();`
                StartAttackHitbox();
            } // end of behavior for CHARGE_SLASH
        }

        private void CHARGE_SLASH_exit()
        {
            // CHARGE_SLASH behavior
            // uml: exit / { EndAttackHitbox(); }
            {
                // Step 1: execute action `EndAttackHitbox();`
                EndAttackHitbox();
            } // end of behavior for CHARGE_SLASH

            this.stateId = StateId.GROUNDED;
        }

        private void CHARGE_SLASH_attack_finished()
        {
            // CHARGE_SLASH behavior
            // uml: ATTACK_FINISHED TransitionTo(IDLE)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                CHARGE_SLASH_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `IDLE`.
                IDLE_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for CHARGE_SLASH

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state DASH
        ////////////////////////////////////////////////////////////////////////////////

        private void DASH_enter()
        {
            this.stateId = StateId.DASH;

            // DASH behavior
            // uml: enter / { StartDash(); }
            {
                // Step 1: execute action `StartDash();`
                StartDash();
            } // end of behavior for DASH
        }

        private void DASH_exit()
        {
            // DASH behavior
            // uml: exit / { EndDash(); }
            {
                // Step 1: execute action `EndDash();`
                EndDash();
            } // end of behavior for DASH

            this.stateId = StateId.GROUNDED;
        }

        private void DASH_attack_press()
        {
            // DASH behavior
            // uml: ATTACK_PRESS TransitionTo(ATTACK_DASH)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                DASH_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `ATTACK_DASH`.
                ATTACK_DASH_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for DASH

            // No ancestor handles this event.
        }

        private void DASH_dash_finished()
        {
            // DASH behavior
            // uml: DASH_FINISHED [move] TransitionTo(RUN)
            if (move)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                DASH_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `RUN`.
                RUN_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for DASH

            // No ancestor handles this event.
        }

        private void DASH_do()
        {
            // DASH behavior
            // uml: do / { UpdateDashTimer(); }
            {
                // Step 1: execute action `UpdateDashTimer();`
                UpdateDashTimer();
            } // end of behavior for DASH

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state IDLE
        ////////////////////////////////////////////////////////////////////////////////

        private void IDLE_enter()
        {
            this.stateId = StateId.IDLE;

            // IDLE behavior
            // uml: enter / { PlayAnim("seq_02_idle"); }
            {
                // Step 1: execute action `PlayAnim("seq_02_idle");`
                PlayAnim("seq_02_idle");
            } // end of behavior for IDLE
        }

        private void IDLE_exit()
        {
            this.stateId = StateId.GROUNDED;
        }

        private void IDLE_attack_press()
        {
            // IDLE behavior
            // uml: ATTACK_PRESS TransitionTo(ATTACK_1)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                IDLE_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `ATTACK_1`.
                ATTACK_1_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for IDLE

            // No ancestor handles this event.
        }

        private void IDLE_charge_release()
        {
            // IDLE behavior
            // uml: CHARGE_RELEASE TransitionTo(CHARGE_SLASH)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                IDLE_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `CHARGE_SLASH`.
                CHARGE_SLASH_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for IDLE

            // No ancestor handles this event.
        }

        private void IDLE_do()
        {
            // IDLE behavior
            // uml: do / { ApplyGroundFriction(); }
            {
                // Step 1: execute action `ApplyGroundFriction();`
                ApplyGroundFriction();
            } // end of behavior for IDLE

            // No ancestor handles this event.
        }

        private void IDLE_move_input()
        {
            // IDLE behavior
            // uml: MOVE_INPUT TransitionTo(RUN)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                IDLE_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `RUN`.
                RUN_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for IDLE

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state RUN
        ////////////////////////////////////////////////////////////////////////////////

        private void RUN_enter()
        {
            this.stateId = StateId.RUN;

            // RUN behavior
            // uml: enter / { PlayAnim("seq_07_run"); }
            {
                // Step 1: execute action `PlayAnim("seq_07_run");`
                PlayAnim("seq_07_run");
            } // end of behavior for RUN
        }

        private void RUN_exit()
        {
            this.stateId = StateId.GROUNDED;
        }

        private void RUN_attack_press()
        {
            // RUN behavior
            // uml: ATTACK_PRESS TransitionTo(ATTACK_RUN)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                RUN_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `ATTACK_RUN`.
                ATTACK_RUN_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for RUN

            // No ancestor handles this event.
        }

        private void RUN_charge_release()
        {
            // RUN behavior
            // uml: CHARGE_RELEASE TransitionTo(CHARGE_SLASH)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                RUN_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `CHARGE_SLASH`.
                CHARGE_SLASH_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for RUN

            // No ancestor handles this event.
        }

        private void RUN_dash_press()
        {
            // RUN behavior
            // uml: DASH_PRESS TransitionTo(DASH)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                RUN_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `DASH`.
                DASH_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for RUN

            // No ancestor handles this event.
        }

        private void RUN_do()
        {
            // RUN behavior
            // uml: do / { ApplyRunVelocity(); }
            {
                // Step 1: execute action `ApplyRunVelocity();`
                ApplyRunVelocity();
            } // end of behavior for RUN

            // No ancestor handles this event.
        }

        private void RUN_stop_input()
        {
            // RUN behavior
            // uml: STOP_INPUT TransitionTo(IDLE)
            {
                // Step 1: Exit states until we reach `GROUNDED` state (Least Common Ancestor for transition).
                RUN_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `IDLE`.
                IDLE_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for RUN

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state WALL_SLIDE
        ////////////////////////////////////////////////////////////////////////////////

        private void WALL_SLIDE_enter()
        {
            this.stateId = StateId.WALL_SLIDE;
        }

        private void WALL_SLIDE_exit()
        {
            this.stateId = StateId.ROOT;
        }

        private void WALL_SLIDE_jump_press()
        {
            // WALL_SLIDE behavior
            // uml: JUMP_PRESS / { ApplyWallJumpImpulse(); } TransitionTo(AIRBORNE)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                ExitUpToStateHandler(StateId.ROOT);

                // Step 2: Transition action: `ApplyWallJumpImpulse();`.
                ApplyWallJumpImpulse();

                // Step 3: Enter/move towards transition target `AIRBORNE`.
                AIRBORNE_enter();

                // Finish transition by calling pseudo state transition function.
                AIRBORNE_InitialState_transition();
                return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
            } // end of behavior for WALL_SLIDE

            // No ancestor handles this event.
        }

        private void WALL_SLIDE_landed()
        {
            // WALL_SLIDE behavior
            // uml: LANDED TransitionTo(GROUNDED)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                ExitUpToStateHandler(StateId.ROOT);

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `GROUNDED`.
                GROUNDED_enter();

                // Finish transition by calling pseudo state transition function.
                GROUNDED_InitialState_transition();
                return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
            } // end of behavior for WALL_SLIDE

            // No ancestor handles this event.
        }

        private void WALL_SLIDE_wall_detach()
        {
            // WALL_SLIDE behavior
            // uml: WALL_DETACH TransitionTo(AIRBORNE)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
                ExitUpToStateHandler(StateId.ROOT);

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `AIRBORNE`.
                AIRBORNE_enter();

                // Finish transition by calling pseudo state transition function.
                AIRBORNE_InitialState_transition();
                return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
            } // end of behavior for WALL_SLIDE

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state ATTACK_GRAB_WALL
        ////////////////////////////////////////////////////////////////////////////////

        private void ATTACK_GRAB_WALL_enter()
        {
            this.stateId = StateId.ATTACK_GRAB_WALL;

            // ATTACK_GRAB_WALL behavior
            // uml: enter / { PlayAnim("seq_18_saber_slash_2"); }
            {
                // Step 1: execute action `PlayAnim("seq_18_saber_slash_2");`
                PlayAnim("seq_18_saber_slash_2");
            } // end of behavior for ATTACK_GRAB_WALL
        }

        private void ATTACK_GRAB_WALL_exit()
        {
            this.stateId = StateId.WALL_SLIDE;
        }

        private void ATTACK_GRAB_WALL_attack_finished()
        {
            // ATTACK_GRAB_WALL behavior
            // uml: ATTACK_FINISHED TransitionTo(GRAB_WALL)
            {
                // Step 1: Exit states until we reach `WALL_SLIDE` state (Least Common Ancestor for transition).
                ATTACK_GRAB_WALL_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `GRAB_WALL`.
                GRAB_WALL_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ATTACK_GRAB_WALL

            // No ancestor handles this event.
        }

        private void ATTACK_GRAB_WALL_do()
        {
            // ATTACK_GRAB_WALL behavior
            // uml: do / { ApplyWallSlideFriction(); }
            {
                // Step 1: execute action `ApplyWallSlideFriction();`
                ApplyWallSlideFriction();
            } // end of behavior for ATTACK_GRAB_WALL

            // No ancestor handles this event.
        }


        ////////////////////////////////////////////////////////////////////////////////
        // event handlers for state GRAB_WALL
        ////////////////////////////////////////////////////////////////////////////////

        private void GRAB_WALL_enter()
        {
            this.stateId = StateId.GRAB_WALL;

            // GRAB_WALL behavior
            // uml: enter / { PlayAnim("seq_12_wall_grab_slide"); }
            {
                // Step 1: execute action `PlayAnim("seq_12_wall_grab_slide");`
                PlayAnim("seq_12_wall_grab_slide");
            } // end of behavior for GRAB_WALL
        }

        private void GRAB_WALL_exit()
        {
            this.stateId = StateId.WALL_SLIDE;
        }

        private void GRAB_WALL_attack_press()
        {
            // GRAB_WALL behavior
            // uml: ATTACK_PRESS TransitionTo(ATTACK_GRAB_WALL)
            {
                // Step 1: Exit states until we reach `WALL_SLIDE` state (Least Common Ancestor for transition).
                GRAB_WALL_exit();

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `ATTACK_GRAB_WALL`.
                ATTACK_GRAB_WALL_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for GRAB_WALL

            // No ancestor handles this event.
        }

        private void GRAB_WALL_do()
        {
            // GRAB_WALL behavior
            // uml: do / { ApplyWallSlideFriction(); }
            {
                // Step 1: execute action `ApplyWallSlideFriction();`
                ApplyWallSlideFriction();
            } // end of behavior for GRAB_WALL

            // No ancestor handles this event.
        }

        // Thread safe. This function can be disabled with `outputStateIdToStringFunction` setting.
        public static string StateIdToString(StateId id)
        {
            switch (id)
            {
                case StateId.ROOT: return "ROOT";
                case StateId.AIRBORNE: return "AIRBORNE";
                case StateId.ATTACK_AIR: return "ATTACK_AIR";
                case StateId.FALL: return "FALL";
                case StateId.JUMP: return "JUMP";
                case StateId.GROUNDED: return "GROUNDED";
                case StateId.ATTACK_1: return "ATTACK_1";
                case StateId.ATTACK_2: return "ATTACK_2";
                case StateId.ATTACK_3: return "ATTACK_3";
                case StateId.ATTACK_DASH: return "ATTACK_DASH";
                case StateId.ATTACK_RUN: return "ATTACK_RUN";
                case StateId.CHARGE_SLASH: return "CHARGE_SLASH";
                case StateId.DASH: return "DASH";
                case StateId.IDLE: return "IDLE";
                case StateId.RUN: return "RUN";
                case StateId.WALL_SLIDE: return "WALL_SLIDE";
                case StateId.ATTACK_GRAB_WALL: return "ATTACK_GRAB_WALL";
                case StateId.GRAB_WALL: return "GRAB_WALL";
                default: return "?";
            }
        }

        // Thread safe. This function can be disabled with `outputEventIdToStringFunction` setting.
        public static string EventIdToString(EventId id)
        {
            switch (id)
            {
                case EventId.APEX: return "APEX";
                case EventId.ATTACK_FINISHED: return "ATTACK_FINISHED";
                case EventId.ATTACK_PRESS: return "ATTACK_PRESS";
                case EventId.CHARGE_RELEASE: return "CHARGE_RELEASE";
                case EventId.DASH_FINISHED: return "DASH_FINISHED";
                case EventId.DASH_PRESS: return "DASH_PRESS";
                case EventId.DO: return "DO";
                case EventId.FALL: return "FALL";
                case EventId.JUMP_PRESS: return "JUMP_PRESS";
                case EventId.LANDED: return "LANDED";
                case EventId.MOVE_INPUT: return "MOVE_INPUT";
                case EventId.STOP_INPUT: return "STOP_INPUT";
                case EventId.WALL_DETACH: return "WALL_DETACH";
                case EventId.WALL_TOUCH: return "WALL_TOUCH";
                default: return "?";
            }
        }

        // Returns the parent state for a given state. Returns ROOT if input has no parent.
        // Thread safe. This function can be disabled with `outputGetParentIdFunction` setting.
        public static StateId GetParentId(StateId id)
        {
            switch (id)
            {
                case StateId.ROOT: return StateId.ROOT;
                case StateId.AIRBORNE: return StateId.ROOT;
                case StateId.ATTACK_AIR: return StateId.AIRBORNE;
                case StateId.FALL: return StateId.AIRBORNE;
                case StateId.JUMP: return StateId.AIRBORNE;
                case StateId.GROUNDED: return StateId.ROOT;
                case StateId.ATTACK_1: return StateId.GROUNDED;
                case StateId.ATTACK_2: return StateId.GROUNDED;
                case StateId.ATTACK_3: return StateId.GROUNDED;
                case StateId.ATTACK_DASH: return StateId.GROUNDED;
                case StateId.ATTACK_RUN: return StateId.GROUNDED;
                case StateId.CHARGE_SLASH: return StateId.GROUNDED;
                case StateId.DASH: return StateId.GROUNDED;
                case StateId.IDLE: return StateId.GROUNDED;
                case StateId.RUN: return StateId.GROUNDED;
                case StateId.WALL_SLIDE: return StateId.ROOT;
                case StateId.ATTACK_GRAB_WALL: return StateId.WALL_SLIDE;
                case StateId.GRAB_WALL: return StateId.WALL_SLIDE;
                default: return StateId.ROOT;
            }
        }
    }
}
